apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
data:
  fluentd.conf: |

    <source>
      @type tail
      path /fluentd/log/nginx/access.log
      pos_file /fluentd/log/nginx/access.log.pos
      tag nginx.access
      format nginx
    </source>

    <match nginx.access>
      @type elasticsearch
      host 34.170.91.218
      user elastic
      password FuiXxiHh8KE=fmE8ZLT+
      logstash_format true
      scheme https
      ssl_verify false
      include_timestamp true
      <buffer>
        flush_interval 10s # for testing
      </buffer>
    </match>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
          - name: logs
            mountPath: /var/log/nginx
        - name: fluentd
          image: us-central1-docker.pkg.dev/terraformcourse-451016/fluentdcustom/fluentcustom
          volumeMounts:
          - name: logs
            mountPath: /fluentd/log/nginx
          - name: fluentd-config
            mountPath: /tmp/fluentd.conf
            subPath: fluentd.conf
          args:
          - "fluentd"
          - "-c"
          - "/tmp/fluentd.conf"
      volumes:
      - name: logs
        emptyDir: {}
      - name: fluentd-config
        configMap:
          name: fluentd-config
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
    - port: 80          
      targetPort: 80  
  type: LoadBalancer  

